### ISSUE TITLE
pytest missing as a dependency on Azure pipeline run

### ISSUE THREAD

**Issue by victoraalves** [conda-forge/polytope-feedstock#3]
### Comment:

Hi,

upon inspecting the failed run from the [Azure pipeline](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=771105&view=results) from yesterday:

```
ERROR: Failure: ModuleNotFoundError (No module named 'pytest')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/conda/feedstock_root/build_artifacts/polytope_1693317066199/test_tmp/tests/polytope_test.py", line 8, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

We can see that it is failing because pytest is missing as a dependency. This dependency (pytest) is stored in the [orginal repo](https://github.com/tulip-control/polytope/blob/main/requirements/README.md) within test.txt.

Maybe modifying the run to only test polytope by importing it might solve the issue?

Thanks!

**Comment by DecBayComp** [comment]
Many thanks @victoraalves for reporting and fixing this issue with PR [!4](https://github.com/conda-forge/polytope-feedstock/pull/4).
